workflows:
    build-ios-workflow:
        name: Cordova iOS Workflow
        max_build_duration: 60
        instance_type: mac_mini
        environment:
            node: latest
            xcode: latest
            cocoapods: default
        triggering:
            events:
                - push
            branch_patterns:
                - pattern: master
                  include: true
                  source: true
        scripts:
            - name: Meteor install and Build
              script: |
                  . ./install_meteor.sh
                  ./meteor remove-platform android
                  ./meteor npm install
                  ./meteor build .build --server https://www.abhakeln.de --architecture os.linux.x86_64
        artifacts:
            - .meteor/local/cordova-build/**/*.ipa
